### ISSUE TITLE
OnMidiDeviceDetachedListener method doesn't called at the screen rotation

### ISSUE THREAD

**Issue by kshoji** [kshoji/USB-MIDI-Driver#38]
The execution of handler on `MidiDeviceConnectionWatcher` is blocked while the screen rotating.
After the new Activity's `onCreate` being called, the handler will be executed.
But the original Activity is already destroyed, so the original Activity can't receive detaching events.

**Comment by planethcom** [comment]
Hi Kaoru

I’d recommend to put all the driver setup into some separate class, a singleton, or all ‘static’ is fine too.

Then initialize that class on startup and destroy everything inside when the app gets terminated.

 

Having the midi setup in an activity is, from the software design point of view, not a very good practice, since there’s no guarantee how long an activity will live. Screen rotation is just one example. 

 

Von: Kaoru Shoji [mailto:notifications@github.com] 
Gesendet: Freitag, 8. Mai 2015 05:24
An: kshoji/USB-MIDI-Driver
Betreff: [USB-MIDI-Driver] OnMidiDeviceDetachedListener method doesn't called at the screen rotation (#38)

 

The execution of handler on MidiDeviceConnectionWatcher is blocked while the screen rotating.
After the new Activity's onCreate being called, the handler will be executed.
But the original Activity is already destroyed, so the original Activity can't receive detaching events.

**Comment by kshoji** [comment]
Hi,
I also think the Activity should not hold MIDI device instances.
Their instances should belong at Application, Service or something static object.

The sample code had written at long ago. It must be refined.

**Comment by planethcom** [comment]
Ah, OK, didn’t know that.

Agree, storing it in a custom application class would be even better than using a regular singleton

 

Von: Kaoru Shoji [mailto:notifications@github.com] 
Gesendet: Freitag, 8. Mai 2015 11:24
An: kshoji/USB-MIDI-Driver
Cc: planethcom
Betreff: Re: [USB-MIDI-Driver] OnMidiDeviceDetachedListener method doesn't called at the screen rotation (#38)

 

Hi,
I also think the Activity should not hold MIDI device instances.
Their instances should belong at Application, Service or something static object.

The sample code had written at long ago. It must be refined.
